name: Android APK

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Unzip project
        run: |
          set -e
          rm -rf project
          unzip -q *.zip -d project

          # מצא את שורש הפרויקט (היכן שנמצא settings.gradle / .kts)
          ROOT_DIR="$(find project -maxdepth 3 -type f \( -name 'settings.gradle' -o -name 'settings.gradle.kts' \) -printf '%h\n' | head -n1)"
          if [ -z "$ROOT_DIR" ]; then
            echo "לא נמצא settings.gradle בתוך ה-ZIP. ודא שה-ZIP הוא פרויקט אנדרואיד תקין."
            exit 1
          fi

          echo "נמצא שורש הפרויקט: $ROOT_DIR"
          echo "PROJ_DIR=$ROOT_DIR" >> "$GITHUB_ENV"

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      # מריץ גריידל גם אם אין gradlew באמצעות התקנת גריידל
      - name: Build Debug APK (Gradle action without wrapper)
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: "8.7"
          build-root-directory: ${{ env.PROJ_DIR }}
          arguments: assembleDebug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: |
            ${{ env.PROJ_DIR }}/**/build/outputs/apk/debug/*.apk
