name: Android APK

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Unzip project
      run: |
        rm -rf project
        unzip -q navon_biznes_android_project.zip -d project || exit 1
        chmod +x project/gradlew || true

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: "17"

    - name: Build Debug APK
      working-directory: project
      run: ./gradlew assembleDebug

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-debug.apk
        path: project/app/build/outputs/apk/debug/*.apk
