name: Android APK

on:
  push:
    branches: ["main"]
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Unzip project
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip
          unzip -o navon_biznes_full_repo.zip -d project

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Build Debug APK (no wrapper)
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: '8.6'     
          build-root-directory: project
          arguments: assembleDebug
          cache-read-only: true

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: project/app/build/outputs/apk/debug/*.apk
