
name: Android APK

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Unzip project
        run: |
          rm -rf project
          unzip -q navon_biznes_android_project.zip -d project
          # אם ה-ZIP פותח תיקיה פנימית אחת עם gradlew – ניישר למבנה "project"
          inner=$(find project -mindepth 1 -maxdepth 1 -type d | head -n1)
          if [ -n "$inner" ] && [ -f "$inner/gradlew" ]; then
            mv "$inner" project_src
            rm -rf project
            mv project_src project
          fi
          chmod +x project/gradlew || true

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build Debug APK
        working-directory: project
        run: ./gradlew assembleDebug

      - name: Upload APK artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: |
            project/**/build/outputs/apk/debug/*.apk
