name: Android APK

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Unzip project
        run: |
          rm -rf project
          unzip -q navon_biznes_android_project.zip -d project
          inner=$(find project -mindepth 1 -maxdepth 1 -type d | head -n1)
          if { [ -n "$inner" ] && [ -f "$inner/settings.gradle" ]; } || { [ -n "$inner" ] && [ -f "$inner/settings.gradle.kts" ]; }; then
            mv "$inner" project_src
            rm -rf project
            mv project_src project
          fi
          chmod -R +x project || true

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Install Gradle (if needed)
        run: |
          if ! command -v gradle >/dev/null 2>&1; then
            sudo apt-get update
            sudo apt-get install -y gradle
          fi
          gradle -v

      - name: Build Debug APK (no wrapper)
        working-directory: project
        run: gradle assembleDebug --no-daemon

      - name: Upload APK artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: project/**/build/outputs/apk/debug/*.apk
